# Site settings
title: Lemon Labs
url: https://lemonlabs.io

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 373f31 #fcee16
  primary-rgb: "252,238,22"
  secondary: 7ac33d
  secondary-dark: 373f31

# Footer settings
footer:
  copyright: Lemon Labs Limited
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/lemonlabsuk
  - title: linkedin
    url: https://www.linkedin.com/company/lemon-labs-limited

# Postal address (add as many lines as necessary)
address:
  - line: Fleet, Hampshire

# Credits content
credits: 'Modified version of the <a href="https://github.com/jeromelachaud/freelancer-theme/blob/master/LICENCE">Apache 2.0</a> licensed <a href="https://github.com/jeromelachaud/freelancer-theme/">freelancer</a> theme for Jekyll'

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-redirect-from
